try clone git again

diff --git a/.github/workflows/cloneGitLab.yml b/.github/workflows/cloneGitLab.yml
--- a/.github/workflows/cloneGitLab.yml
+++ b/.github/workflows/cloneGitLab.yml
@@ -13,6 +13,16 @@ jobs:
       - name: Checkout the current repository
         uses: actions/checkout@v2
 
+      - name: Install Speedtest
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y openvpn speedtest-cli
+
+      - name: Measure Speed Before VPN
+        run: |
+          speedtest-cli --json > $HOME/speedtest_before_start_vpn.json
+          cat $HOME/speedtest_before_start_vpn.json
+
       - name: Install OpenVPN
         run: |
           sudo apt update -y
@@ -26,83 +36,89 @@ jobs:
 
       - name: Start OpenVPN
         run: |
-          for i in {1..5}; do
-            sudo nohup openvpn --verb 4 --config $(pwd)/${{ secrets.VPN_OVPN }} --auth-user-pass $(pwd)/${{ secrets.VPN_AUTHOR }} > $HOME/openvpn.log 2>&1 &
-            echo "$(curl -Is ${{ secrets.KIBANA }} | head -1)"
-            cat $HOME/openvpn.log
-            if grep -q "Initialization Sequence Completed" $HOME/openvpn.log || grep -q "Peer Connection Initiated with" $HOME/openvpn.log; then
-              echo "OpenVPN started successfully."
-              break
-            fi
-            echo "OpenVPN start failed, retrying..."
-            sudo pkill -f openvpn
-          done
+          sudo nohup openvpn --verb 4 --config $(pwd)/${{ secrets.VPN_OVPN }} --auth-user-pass $(pwd)/${{ secrets.VPN_AUTHOR }} > $HOME/openvpn.log 2>&1 &
+          cat $HOME/openvpn.log
 
       - name: Clone GitLab repository
-        run: git clone ${{ secrets.GITLAB_REPOSITORY }} GoSELL-Automation
+        run: |
+          for i in {1..5}; do
+            git clone ${{ secrets.GITLAB_REPOSITORY }} GoSELL-Automation
+            if [ $? -eq 0 ]; then
+              echo "Git clone successful"
+              git log -1
+            else
+              echo "Git clone failed"
+            fi
+            cat $HOME/openvpn.log
+          done
 
       - name: Stop OpenVPN
         run: |
           sudo pkill -f openvpn
 
-      - name: Switch to another branch
-        run: |
-          cd GoSELL-Automation
-          git checkout GoSELL-Thang
+      - name: Measure Speed After Stop VPN
+        run: |     
+          speedtest-cli --json > $HOME/speedtest_after_stop_vpn.json
+          cat $HOME/speedtest_after_stop_vpn.json
 
-      - name: Set up Java
-        uses: actions/setup-java@v3
-        with:
-          java-version: '22'
-          distribution: 'adopt'
-
-      - name: Install FFmpeg
-        run: sudo apt-get update && sudo apt-get install -y ffmpeg
-
-      - name: Cache Maven packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-ubuntu
-          restore-keys: |
-            ${{ runner.os }}-maven-
-
-      - name: Cache Maven packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-ubuntu
-          restore-keys: |
-            ${{ runner.os }}-maven-ubuntu
-
-      - name: Install dependencies
-        run: |
-          cd GoSELL-Automation
-          mvn install -DskipTests
-
-      - name: Run tests
-        run: |
-          cd GoSELL-Automation
-          mvn --batch-mode test "-DsuiteFile=test_config/web/createProductTest.xml"
-
-      - name: Upload all recording .mp4 files
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: MP4 Files
-          path: '**/*.mp4'
-
-      - name: Upload Test Report
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: Test Reports
-          path: |
-            **/html/index.html
-            **/reportng.css
-            **/reportng.js
-            **/suite*_test*_results.html
-
-      - name: Remove cloned repo
-        run: |
-          rm -r GoSELL-Automation
+#      - name: Switch to another branch
+#        run: |
+#          cd GoSELL-Automation
+#          git checkout GoSELL-Thang
+#
+#      - name: Set up Java
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '22'
+#          distribution: 'adopt'
+#
+#      - name: Install FFmpeg
+#        run: sudo apt-get update && sudo apt-get install -y ffmpeg
+#
+#      - name: Cache Maven packages
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-ubuntu
+#          restore-keys: |
+#            ${{ runner.os }}-maven-
+#
+#      - name: Cache Maven packages
+#        uses: actions/cache@v3
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-ubuntu
+#          restore-keys: |
+#            ${{ runner.os }}-maven-ubuntu
+#
+#      - name: Install dependencies
+#        run: |
+#          cd GoSELL-Automation
+#          mvn install -DskipTests
+#
+#      - name: Run tests
+#        run: |
+#          cd GoSELL-Automation
+#          mvn --batch-mode test "-DsuiteFile=test_config/web/createProductTest.xml"
+#
+#      - name: Upload all recording .mp4 files
+#        if: always()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: MP4 Files
+#          path: '**/*.mp4'
+#
+#      - name: Upload Test Report
+#        if: always()
+#        uses: actions/upload-artifact@v3
+#        with:
+#          name: Test Reports
+#          path: |
+#            **/html/index.html
+#            **/reportng.css
+#            **/reportng.js
+#            **/suite*_test*_results.html
+#
+#      - name: Remove cloned repo
+#        run: |
+#          rm -r GoSELL-Automation
